### PR TITLE
add missing multiplicity to solvent impurities DBs

### PR DESCRIPTION
**Pull request by jobo322**

### CODE REVIEW

**Comment by targos** [comment]
It seems that this only changes the precision of the numbers, and in a weird way (two digits are removed inside the decimals):

CleanShot 2023-06-13 at 09 04 52

How does that happen?

**Comment by jobo322** [comment]
> It seems that this only changes the precision of the numbers, and in a weird way (two digits are removed inside the decimals):
> 
> CleanShot 2023-06-13 at 09 04 52
> 
> How does that happen?

we generate the range with:
- https://github.com/cheminfo/nmr-processing/blob/main/src/signals/signalsToRanges.ts#L1-L79

the properties `from` and `to` is calculated with:

- https://github.com/cheminfo/nmr-processing/blob/main/src/utilities/rangeFromSignal.ts#L1-L59

**Comment by targos** [comment]
Can you tell what change is responsible for the new numbers?

**Comment by lpatiny** [comment]
The generation of the database was done once 2 years ago and it involves signalToRange (that allows to find the area from / to corresponding to the integration). We enlarged a little bit the integration area and this is likely the reason we have this difference.

**Pull request merged**
